# Generated by Django 2.0.10 on 2019-02-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authos',
            new_name='author',
        ),
    ]
